version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.6.16
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - grafana_network
      - grafana_prometheus
      - vm_network


networks:
  grafana_network:
    name: grafana_network
    driver: bridge

  grafana_prometheus:
    name: grafana_prometheus
    external: true

  vm_network:
    name: vm_network
    external: true

volumes:
  grafana_data:


